driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: test/fixtures/environments
  nodes_path: test/fixtures/nodes
  client_rb:
    environment: default

platforms:
  - name: centos-7.3

suites:
  - name: client
    run_list:
    - recipe[postfix::client]
